#################################################
# DO NOT CHANGE 
CONFIG_NAME: 'text-to-image'

DATASET_NAME: 'birds'
EMBEDDING_TYPE: 'cnn-rnn'
DATA_DIR: 'data/birds'

IMAGE_SIZE: 256
WRONG_CAPTION: 9

R_PRECISION_DIR: './evaluation'
R_PRECISION_FILE: 'r_precision.npz'
R_PRECISION_FILE_HIDDEN: 'r_precision_hidden.npz'
CHECKPOINT_DIR: './checkpoint'
CHECKPOINT_NAME: 'model.ckpt'
#################################################


GPU_ID: '0'
WORKERS: 4

BATCH_SIZE: 64


TRAIN:
    FLAG: True
    MAX_EPOCH: 600
    
    
#################################################
# DO NOT CHANGE 
TEST:
    B_EXAMPLE: False
    GENERATED_TEST_IMAGES: './evaluation/generated_images'
    GENERATED_HIDDEN_TEST_IMAGES: './evaluation/generated_images_hidden'
#################################################


GAN:
    Z_DIM: 512
    
    
#################################################
# DO NOT CHANGE 
TEXT:
    CAPTIONS_PER_IMAGE: 10
#################################################
    WORDS_NUM: 20
    EMBEDDING_DIM: 128
